In [2]:
import numpy as np

In [7]:
a = np.add(50,25)
b = np.subtract(50,25)
c = np.multiply(50,25)
d = np.divide(50,25)

print(a)
print(b)
print(c)
print(d)

75
25
1250
2.0


In [10]:
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,2,3,4])

newarr = np.multiply(arr1,arr2)

print(newarr)

[ 2  8 18 32]


In [11]:
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,2,3,4])

newarr = np.add(arr1,arr2)

print(newarr)

[ 3  6  9 12]


In [12]:
arr = np.array([2,4,6,8])

newarr = np.sum(arr)

print(newarr)

20


In [13]:
arr = np.array([2,4,6,8])

newarr = np.min(arr)

print(newarr)

2


In [14]:
arr = np.array([2,4,6,8])

newarr = np.max(arr)

print(newarr)

8


In [15]:
arr = np.array([2,4,6,8])

newarr = np.mean(arr)

print(newarr)

5.0


In [19]:
arr = np.array([9,16,10])

newarr = np.sqrt(arr)

print(newarr)

[3.         4.         3.16227766]


In [20]:
arr = np.array([19,16,10, 50, 2, 29])

newarr = np.sort(arr)

print(newarr)

[ 2 10 16 19 29 50]


In [27]:
arr = np.array(["Zunaib", "Ahmed", "Bilal", "Sunny", "Uroosa", "Nabiha", "Moeed"])

newarr = np.sort(arr)

print(newarr)

['Ahmed' 'Bilal' 'Moeed' 'Nabiha' 'Sunny' 'Uroosa' 'Zunaib']
