In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [5]:
print(arr[1])

2


In [6]:
print(arr.ndim)

1


In [7]:
arr = np.array(50)
print(arr)

50


In [8]:
print(arr.ndim)

0


In [9]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [11]:
print(arr[1] + arr[3])

6


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
print(arr.ndim)

2


In [23]:
print(arr[0,3])

4


In [34]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
print(arr[0:2,2:4])

[[3 4]
 [8 9]]


In [38]:
print(arr[0:2,2:4].ndim)

2


In [41]:
print(arr[0,1])
print(arr[0,1].ndim)

2
0


In [42]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

arr[0] = 42

print(arr)

print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [50]:
arr = np.array([[5, 3, 3],[1, 2, 3],[1, 2, 3]])

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[[5 3 3]
 [1 2 3]
 [1 2 3]]
2
9
(3, 3)


In [51]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view()

arr[0] = 42

print(arr)

print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [56]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

arr[0] = 42

print(arr)

print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [57]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [58]:
arr = np.array([[5, 3, 3],[1, 2, 3],[1, 2, 3]])

print(arr)
print(arr.shape)

[[5 3 3]
 [1 2 3]
 [1 2 3]]
(3, 3)


In [69]:
arr = np.array([1, 2, 3, 4,5,6,7,8,9])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
