# Numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.15.4


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 0-Dimensional Arrays:

In [6]:
arr = np.array(42)
print(arr)

42


# 1-Dimensional Arrays:

In [7]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2-Dimensional Arrays:

In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3-Dimensional Arrays:

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [16]:
print(arr*3)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [21]:
#0-D Array
a = np.array(42)

#1-D Array
b = np.array([1,2,3,4,5])

#2-D Array
c = np.array([[1,2,3],[4,5,6]])

#3-D Array
d = np.array([[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]])


#1-D Array
print(b.ndim)

#2-D Array
print(c.ndim)

#0-D Array
print(a.ndim)

#3-D Array
print(d.ndim)

1
2
0
3


In [25]:
print(a)

42
